### ISSUE TITLE
Ruby upgrade error

### ISSUE THREAD

**Issue by alicebob** [poise/poise-ruby-build#8] opened 2017-03-31 08:23 UTC
I tried updating a ruby from 2.3.1 to 2.3.3 for a failed install. I got this error:

```
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/poise-ruby-build/files/halite_gem/poise_ruby/ruby_build/provider.rb:214:in `uninstall_ruby'
      
      directory("/opt/ruby_build/builds/myapp") do
        action [:delete]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        path "/opt/ruby_build/builds/myapp"
        declared_type :directory
        cookbook_name "mycookbook"
      end
      
      Platform:
      ---------
      x86_64-linux
      
    
    ================================================================================
    Error executing action `install` on resource 'application_ruby[myapp]'
    ================================================================================
    
    Errno::ENOTEMPTY
    ----------------
    directory[/opt/ruby_build/builds/dashboard] (/var/chef/cache/cookbooks/poise-ruby-build/files/halite_gem/poise_ruby/ruby_build/provider.rb line 214) had an error: Errno::ENOTEMPTY: Directory not empty @ dir_s_rmdir - /opt/ruby_build/builds/myapp

```

Deleting `/opt/ruby_build/builds/myapp` solved the issue, but it seemed to want to delete too much anyway.

Thanks!

**Comment by coderanger** [comment] 2017-04-03 23:54
What was left in that folder?

**Comment by alicebob** [comment] 2017-04-04 14:14
I did not save the directory, just removed it and moved on :(

**Comment by alfrego129** [comment] 2017-07-11 14:49
My problem is that

I use Kali Linux and I am trying to use the tool of "beef", however, for this situation firstly I need to upgrade ruby because I see this error 'Ruby version 2.1.5 is no longer supported. Please upgrade to Ruby version 2.2 or later.'

When I check my version of the ruby it is 'ruby 2.1.5p273 (2014-11-13) [i386-linux-gnu]'.

And then I tried respectively

sudo apt-get install ruby2.0

sudo apt-get install ruby-full

apt-get upgrade

apt-get update

But still I could not upgrade it, how can I upgrade, could you help me, please?

Thank you.

**Comment by coderanger** [comment] 2017-07-11 18:04
@alfrego129 That has nothing to do with this issue, and doesn't appear to have anything to do with Chef or Poise-Ruby.

**Comment by coderanger** [comment] 2017-07-11 18:04
Closing this out as unreproducible at this time.

**Closed as completed by coderanger** 2017-07-11 18:04 UTC
